### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by cuongngoz** [sindresorhus/p-limit#39]
```
Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR

>> /home/travis/build/alaa/tesh/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
>>         } catch {}
>>                 ^
>> 
>> SyntaxError: Unexpected token {
>>   at createScript (vm.js:80:10)
>>   at Object.runInThisContext (vm.js:139:10)
>>   at Module._compile (module.js:617:28)
>>   at Object.Module._extensions..js (module.js:664:10)
>>   at Module.load (/home/travis/build/alaa/tesh/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at tryModuleLoad (module.js:506:12)
>>   at Function.Module._load (module.js:498:3)
>>   at Module.require (module.js:597:17)
>>   at require (internal/module.js:11:18)
>>   at Object.<anonymous> (/home/travis/build/alaa/tesh/node_modules/terser-webpack-plugin/dist/index.js:26:38)
>>   at Module._compile (module.js:653:30)
>>   at Object.Module._extensions..js (module.js:664:10)
>>   at Module.load (/home/travis/build/alaa/tesh/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at tryModuleLoad (module.js:506:12)
>>   at Function.Module._load (module.js:498:3)
>>   at Module.require (module.js:597:17)
>>   at require (internal/module.js:11:18)
>>   at Object.<anonymous> (/home/travis/build/alaa/tesh/node_modules/terser-webpack-plugin/dist/cjs.js:3:16)
>>   at Module._compile (module.js:653:30)
>>   at Object.Module._extensions..js (module.js:664:10)
>>   at Module.load (/home/travis/build/alaa/tesh/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at tryModuleLoad (module.js:506:12)
>>   at Function.Module._load (module.js:498:3)
>>   at Module.require (module.js:597:17)
>>   at require (internal/module.js:11:18)
>>   at Object.<anonymous> (/home/travis/build/alaa/tesh/webpack.buildconfig.js:3:22)
>>   at Module._compile (module.js:653:30)
>>   at Object.Module._extensions..js (module.js:664:10)
>>   at Module.load (/home/travis/build/alaa/tesh/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at tryModuleLoad (module.js:506:12)
>>   at Function.Module._load (module.js:498:3)
>>   at Module.require (module.js:597:17)
>>   at require (internal/module.js:11:18)
>>   at /home/travis/build/alaa/tesh/webpack.config.js:4:12
>>   at Object.<anonymous> (/home/travis/build/alaa/tesh/webpack.config.js:5:2)
>>   at Module._compile (module.js:653:30)
>>   at Object.Module._extensions..js (module.js:664:10)
>>   at Module.load (/home/travis/build/alaa/tesh/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>>   at tryModuleLoad (module.js:506:12)
>>   at Function.Module._load (module.js:498:3)
>>   at Module.require (module.js:597:17)
>>   at require (internal/module.js:11:18)
>>   at Object.module.exports (/home/travis/build/alaa/tesh/Gruntfile.js:9:25)
>>   at loadTask (/home/travis/build/alaa/tesh/node_modules/grunt/lib/grunt/task.js:315:10)
>>   at Task.task.init (/home/travis/build/alaa/tesh/node_modules/grunt/lib/grunt/task.js:434:5)
>>   at Object.grunt.tasks (/home/travis/build/alaa/tesh/node_modules/grunt/lib/grunt.js:111:8)
>>   at Liftoff.<anonymous> (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/grunt-cli/bin/grunt:66:13)
>>   at Liftoff.execute (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:203:12)
>>   at module.exports (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/grunt-cli/node_modules/flagged-respawn/index.js:51:3)
>>   at Liftoff.<anonymous> (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:195:5)
>>   at Liftoff.<anonymous> (/home/travis/.nvm/versions/node/v8.12.0/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:170:7)
>>   at _combinedTickCallback (internal/process/next_tick.js:132:7)
>>   at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by sindresorhus** [comment]
Duplicate of #33
