### ISSUE TITLE
Jest giving error - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by rahul-desai3** [sindresorhus/p-limit#69]
I am using -
p-limit@4.0.0
jest@24.9.0

npm v8.15.0
node v16.17.0

Jest error:
```
 FAIL  src/components/livelink/GenerateLiveLink/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/rahuldesai/falcon-ui/node_modules/p-limit/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import Queue from 'yocto-queue';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import moment from 'moment-timezone';
    > 2 | import pLimit from 'p-limit';
        | ^
      3 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/ducks/inventory/softwareTable/index.js:2:1)
```

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by aaarichter** [comment]
I'm running into the same issue. @sindresorhus even though this is a nice guide, applying these changes won't help with your module.

**Comment by aaarichter** [comment]
https://github.com/sindresorhus/ky-universal/issues/35#issue-899739560 - @rahul-desai3 when you use this recipe, change the `transformIgnorePatterns` option to

```
transformIgnorePatterns: ["/node_modules/(?!(p-limit|yocto-queue))"],
```
