### ISSUE TITLE
v5 can break due to subpath imports - node+deno unable to resolve core modules re imports map

### ISSUE THREAD

**Issue by firxworx** [sindresorhus/p-limit#75]
I reported this: https://github.com/nodejs/node/issues/51009
initially reported to tsx here: https://github.com/privatenumber/tsx/issues/425

The minimal repro from the tsx issue (on StackBlitz) uses `p-limit` for the demo.

I encountered the issue when bumping packages in a TypeScript cli project to current (including bumping p-limit v4 to v5) that runs via `tsx` (with `module` "ESNext" in the tsconfig).

The trigger of the issue in p-limit is right here: 
https://github.com/sindresorhus/p-limit/compare/v4.0.0...v5.0.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R2

Given the circumstances I'm not sure if you want to do anything differently, however I figured I'd create an issue here to put it on your radar, in case you want to accommodate on account of the popularity of this package. Thanks!

**Comment by JonathonRP** [comment]
Someone else reported a similar issue with esbuild

**Comment by firxworx** [comment]
@JonathonRP gotcha, thanks for the tip

Note tsx uses esbuild under the hood and is what I was using that led to me encountering + reporting this issue in the first place.

For future note if you comment with the issue link (or link direct to the specific comment), or if you reference the issue id, GitHub will take care of adding the mention to the issue feeds. Its fewer keystrokes than typing out "someone else reported..." and has the benefit of linking things up and tying them together :)

I'm going to comment over on #76 now how this is related

**Comment by dsherret** [comment]
To be clear, Deno is not affected because of the subpath imports. The issue is async_hooks is experimental API that Node recommends migrating away from (https://nodejs.org/api/async_hooks.html) and Deno does not support it.

The following change to the package.json makes it "work" in Deno:

```
    "imports": {
		"#async_hooks": {
			"deno": "./async-hooks-stub.js",
			"node": "async_hooks",
			"default": "./async-hooks-stub.js"
		}
	}
```

**Comment by segevfiner** [comment]
Seems to also fail in tsup with:
```
ESM Build failed
Error: Build failed with 1 error:
../../node_modules/.pnpm/p-limit@5.0.0/node_modules/p-limit/index.js:2:28: ERROR: Could not resolve "#async_hooks"
    at failureErrorWithLog (/Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/segevfiner/prj/swimm/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
CJS Build failed
```

**Comment by firxworx** [comment]
@segevfiner for sure thanks for the explicit confirmation.

tsup uses esbuild, the same as tsx (which is what I was using when I first hit and reported this issue) so unfortunately this can be expected. You can downgrade p-limit to v 4.x and it should work for you.

**Comment by narthur** [comment]
I had a similar issue using tsx with p-limit v5. Downgrading to v4 fixed the issue (thanks @firxworx!)

Here's the error I had to help other people searching:

```
node:internal/url:1393
    throw new ERR_INVALID_URL_SCHEME('file');
          ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at fileURLToPath (node:internal/url:1393:11)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1164:20)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1106:16)
    at a._resolveFilename (/Users/work/ProgrammingProjects/[...]/node_modules/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Queue (/Users/work/ProgrammingProjects/[...]/node_modules/.pnpm/p-limit@5.0.0/node_modules/p-limit/index.js:2:29)
    at Object.<anonymous> (/Users/work/ProgrammingProjects/[...]/node_modules/.pnpm/p-limit@5.0.0/node_modules/p-limit/index.js:4:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'ERR_INVALID_URL_SCHEME'
}

Node.js v20.11.0
```

**Comment by segevfiner** [comment]
Seems like it is an issue in Node.js itself: https://github.com/nodejs/node/issues/49257

**Comment by crypt0miester** [comment]
hello, using `patch-package` you can do the following:
```
diff --git a/node_modules/p-limit/index.js b/node_modules/p-limit/index.js
-import {AsyncResource} from '#async_hooks';
+import {AsyncResource} from './async-hooks-stub';
```

hope that helps someone until the issue is resolved.

**Comment by fer-ri** [comment]
> hello, using `patch-package` you can do the following:
> 
> ```
> diff --git a/node_modules/p-limit/index.js b/node_modules/p-limit/index.js
> -import {AsyncResource} from '#async_hooks';
> +import {AsyncResource} from './async-hooks-stub';
> ```
> 
> hope that helps someone until the issue is resolved.

Thanks, it helped me. 

For clarity, I manually edited the `node_modules/p-limit/index.js` file and changed this part to `import {AsyncResource} from './async-hooks-stub';`

**Comment by sindresorhus** [comment]
The latest version no longer uses subpath exports: https://github.com/sindresorhus/p-limit/releases/tag/v6.0.0
